"""add status and is_deleted columns

Revision ID: a1e12397b79c
Revises: 4721e04c2686
Create Date: 2025-04-22 23:59:56.488963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1e12397b79c"
down_revision: Union[str, None] = "4721e04c2686"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="status"),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column(
        "students",
        sa.Column("is_deleted", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "is_deleted")
    op.drop_column("students", "status")
    # ### end Alembic commands ###
