name: Ruff

on: [push, pull_request]

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip & install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Ruff Lint Check
        run: ruff check .

  format_check:
    name: Check Code Format with Ruff
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Ruff Format Check
        run: ruff format --check

  typecheck:
    name: Static Type Checking with Pyright
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Python dependencies (for Pyright)
        run: pip install -r requirements.txt
      - name: Install Pyright
        run: npm install -g pyright
      - name: Run Pyright
        run: pyright

  unit_testing:
    name: Run Unit Tests with Pytest
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    env:
      DATABASE_URL: 'sqlite+aiosqlite:///:memory:'
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx aiosqlite
      - name: Run tests
        run: pytest -v


