name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
        python -m pip install --upgrade pip
        pip install ruff
      - name: Analysing the code with ruff
        run: |
          ruff check
      